INSERT INTO stations_stationnetwork (code, name) VALUES ('AAE', 'Geophysical Observatory, Adis Abeba University, Ethiopia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('AAM', 'University of Michigan, Ann Arbor, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ACI', 'Universiti Calabria, Cosenza, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ACP', 'Autoridad del Canal de PanamBalboa-AncPanama');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ADE', 'Primary Industries and Resources SA, Adelaide, SA, Australia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('AGS', 'USGS Alaska Seismic Project, Menlo Park, California, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ALG', 'CRAAG, Alger-Bouzareah, Algeria');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ALQ', 'USGS Albuquerque Seismological Laboratory, Albuquerque, New Mexico, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ANZA', 'Anza Seismic Network, IGPP, UC San Diego, La Jolla, Calif, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ARO', 'Observatoire Ghysique d''Arta, Djibouti');
INSERT INTO stations_stationnetwork (code, name) VALUES ('AS', 'Modified High Gain Long Period Network (ASRO), Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ASRS', 'GSRAS Siberian Branch, Altay-Sayan Reg. Seis. Ctr., Novosibirsk, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ATH', 'National Observatory of Athens, Greece');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ATL', 'Georgia Institute of Technology, Atlanta, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ATX', 'University of Texas Institute for Geophysics, Austin, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('AUST', 'Geoscience Australia, Canberra, ACT, Australia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('AWIB', 'Alfred Wegener Inst. of Polar and Marine Research, Bremerhaven, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('AZER', 'Republic Center of Seismic Survey, Azerbaijan Academy of Science, Baku');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BARI', 'Osservatorio Sismologico, Universitegli Studi di Bari, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BASV', 'British Antarctic Survey, Cambridge, England, UK');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BDF', 'Observat Sismolo, Universidade de Brasa, Brazil');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BELR', 'Inst. of Geochemistry and Geophysics, Belarus Academy of Science, Minsk');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BEO', 'Seismological Survey of Serbia, Belgrade, Serbia and Montenegro');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BER', 'Institutt for geovitenskap, Universitetet i Bergen, Norway');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BGRD', 'Bundesanstalt fwissenschaften und Rohstoffe, Hannover, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BGS', 'British Geological Survey, Edinburgh, Scotland, UK');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BHD', 'Seismology Unit, Scientific Research Council, Baghdad, Iraq');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BHKY', 'University of Kentucky, Lexington, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BHL', 'Conseil National de la Recherche Scientifique, Beirut, Lebanon');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BJI', 'Institute of Geophysics, China Earthquake Administration, Beijing');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BK', 'Berkeley Digital Seismograph Network, California, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BKK', 'Meteorological Department, Bangkok, Thailand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BKN', 'Procurement Executive, Ministry of Defence, Blacknest, England, UK');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BLA', 'Virginia Polytechnic Institute and State University, Blacksburg, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BLMY', 'Indian Point Network, Woodward-Clyde Consultants, New Jersey, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BMU', 'Bahrain Meteorological Service, Bahrain');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BNG', 'Inst. de Recherche pour le Developpement, Bangui, Central African Rep.');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BNS', 'Geologisches Inst. der UniversitK Bergisch Gladbach, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BOG', 'Instituto Geofco, Universidad Javeriana, BogotColombia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BOU', 'University of Colorado, Boulder, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BRA', 'Geofyziky  SAV, Bratislava, Slovakia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BRK', 'University of California, Berkeley, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BRL', 'Freie UniversitBerlin, Berlin, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BRS', 'University of Queensland, Brisbane, Australia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BSE', 'Boise State University, Idaho, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BUC', 'National Institute for Earth Physics, Bucharest-Magurele, Romania');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BUD', 'Hungarian Seismological Institute, Budapest, Hungary');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BUG', 'Ruhr-Universit Bochum, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BUL', 'Goetz Observatory, Bulawayo, Zimbabwe');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BUT', 'Montana Bureau of Mines and Geology, Butte, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BYKL', 'GSRAS Siberian Branch, Baykal Regional Seis. Center, Irkutsk, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('BYT', 'Central Institute of Mines, Katowice, Poland');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CAM', 'Massachusetts Institute of Technology, Cambridge, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CAN', 'Australian National University, Canberra, ACT, Australia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CAR', 'FUNVISIS, Caracas, Venezuela');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CAT', 'Istituto Scienze della Terra, Catania, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CD', 'China Digital Broadband Seismic Network (CDSN), Beijing, China');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CDMG', 'California Division of Mines and Geology, Sacramento, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CDPJ', 'Nat. Research Ctr for Disaster Prevention, Ibaraki-ken, Japan--now NIED');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CDR', 'Commissariat a l''Energie Atomique (CEA), Fontenay aux Roses, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CDWR', 'California Department of Water Resources, Sacramento, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CELS', 'Comisiidroelectrica del Rio Lempa, El Salvador');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CERI', 'Center for Earthquake Research and Information, Memphis, Tennessee, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CFF', 'Inst. et Observatoire de Physique du Globe, Clermont-Ferrand, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CHC', 'University of North Carolina, Chapel Hill, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CIG', 'Cen. de Investigaciones Geotecnicas, San Salvador, El Salvador (closed)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CLE', 'John Carroll University, Cleveland, Ohio, USA (closed)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CLTN', 'GSC Charlevoix Local Telemetered Network, Ottawa, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CN', 'Canadian National Seismic Network (CNSN) BB stations, Ottawa, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CNRM', 'Centre National de la Recherche Scient. et Tech., Rabat, Morocco');
INSERT INTO stations_stationnetwork (code, name) VALUES ('COR', 'College of Oceanography, Oregon State University, Corvallis, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CRT', 'Instituto Andaluz de Geofca, Universidad de Granada, Spain');
INSERT INTO stations_stationnetwork (code, name) VALUES ('CSC', 'University of South Carolina, Columbia, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DAL', 'Southern Methodist University, Dallas, Texas, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DBN', 'Koninkijk Nederlands Meteorologisch Instituut, De Bilt, Netherlands');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DDA', 'Directorate of Disaster Affairs, Lodumlu, Ankara, Turkey');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DESU', 'CADAFE, Desarrollo Uribante Caparo (DESURCA), San Crist, Venezuela');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DHMR', 'National Seismological Observatory Center, Dhamar, Yemen');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DIAS', 'Dublin Institute for Advanced Studies, Ireland');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DJA', 'Badan Meteorologi dan Geofisika, Jakarta, Indonesia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DMN', 'Department of Mines and Geology, Kathmandu, Nepal');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DNGM', 'Direc Nacional de Geologia, Maputo, Mozambique');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DNK', 'Danmarks og Grds Geologiske Underse, Copenhagen, Denmark');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DRI', 'Disaster Prevention Research Institute, Kyoto University, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DRS', 'GSRAS, Dagestan Regional Seismological Center, Makhachkala, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DSIT', 'State Water Works Division (DSI), Ankara, Turkey');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DTM', 'Carnegie Institution of Washington, Washington DC, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DUKE', 'Duke Power Company, South Carolina, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('DW', 'Digital Worldwide Std. Seismograph Network (DWSSN), Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ECTN', 'GSC Eastern Canada Telemetered Network, Ottawa, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ECX', 'RESNOM, CICESE, Ensenada, Baja California, Mexico');
INSERT INTO stations_stationnetwork (code, name) VALUES ('EDM', 'University of Alberta, Edmonton, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ENI', 'Ente Nazionale Idrocarburi, Rome, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ENT', 'Geological Survey and Mines Department, Entebbe, Uganda');
INSERT INTO stations_stationnetwork (code, name) VALUES ('EPT', 'Kidd Seismological Observatory, University of Texas, El Paso, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ERC', 'Centro Ettore Majorana, Erice, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ERIJ', 'Earthquake Research Institute, Univ. of Tokyo, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('EUO', 'Department of Geological Sciences, University of Oregon, Eugene, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('FBB', 'Geologisches Landesamt Baden-Wberg (LEDBW), Freiburg, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('FDF', 'IPG Observatoire Ghysique, St. Pierre, Martinique');
INSERT INTO stations_stationnetwork (code, name) VALUES ('FLAG', 'Arizona Earthquake Information Center, Flagstaff, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('FNET', 'F-net Broadband Seismograph Network, University of Tokyo, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('FOG', 'Osservatorio V. Nigri, Foggia, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('FR', 'Rau National de Surveillance Sismique (ReNaSS), Strasbourg, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('FUR', 'Geophysikalisches Obs. der Univ. M, Ffeldbruck, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GAR', 'Complex Seismological Expedition, Garm, Tajikistan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GBZT', 'TUBITAK, Marmara Research Center, Gebze, Turkey');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GCG', 'INSIVUMEH, Guatemala City, Guatemala');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GE', 'GEOFON (GeoForschungsNetz) Program, Potsdam, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GEN', 'Dipart. Studio del Territorio e Risorse, Universiti Genova, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GEOS', 'Programme GEOSCOPE, Paris, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GEOT', 'Teledyne Geotech Corporation, Garland, Texas, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GFU', 'Geofyzikstav Akademie vCeskepubliky, Praha, Czech Republic');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GIA', 'Geophysical Institute, University of Alaska, Fairbanks, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GII', 'Geophysical Institute of Israel, Lod, Israel');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GOL', 'Geophysics Department, Colorado School of Mines, Golden, Colorado, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GOM', 'Observatoire Volcanologique de Goma, Goma, Dem. Republic of the Congo');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GR', 'German Regional Seismic Network (GRSN), Hannover, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GRF', 'BGR, Zentralobservatorium Grnberg, Erlangen, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GRN', 'Lab. de Ghysique Interne et de Tectonophysique, Grenoble, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GSDM', 'Geological Survey Department of Malawi, Zomba, Malawi');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GT', 'Global Telemetered Seismic Network (GTSN), Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GUC', 'Departamento de Geofca, Universidad de Chile, Santiago, Chile');
INSERT INTO stations_stationnetwork (code, name) VALUES ('GUV', 'CVG Electrificacion del CaronEDELCA), Guri, Venezuela');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HACU', 'Hacettepe University, Ankara, Turkey');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HDC', 'Universidad Nacional, Campus Omar Dengo, Heredia, Costa Rica');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HEL', 'Seismologian Laitos, Helsingin Yliopisto, Helsinki, Finland');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HFS', 'The Swedish Defence Research Agency, FOI, Stockholm, Sweden');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HG', 'High Gain Long Period Network (HGLP), Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HIG', 'Hawaii Institute of Geophysics, Honolulu, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HKC', 'Hong Kong Observatory, Kowloon, Hong Kong, China');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HKT', 'University of Texas Marine Science Institute, Galveston, USA (now ATX)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HLW', 'National Research Institute of Astronomy and Geophysics, Helwan, Egypt');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HNR', 'Ministry of Natural Resources, Honiara, Solomon Islands');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HON', 'NOAA, Pacific Tsunami Warning Center, Ewa Beach, Hawaii, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HRS', 'Earthquake and Volcano Observatory, Hirosaki University, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HSS', 'Inst. of Seismology and Volcanology, Hokkaido Univ., Sapporo, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HVO', 'USGS Hawaiian Volcano Observatory, Hawaii, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('HYB', 'National Geophysical Research Institute, Hyderabad, India');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IC', 'IRIS/USGS China Digital Broadband Seismic Network, Beijing, China');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ICE', 'Instituto Costariccense de Electricidad, San JosCosta Rica');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ID', 'Project IDA (Intl. Deployment of Accelerometers), San Diego, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IGIL', 'Inst. Geofco do Infante D. Luis, Univ. de Lisboa, Lisbon, Portugal');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IGSN', 'IRIS Global Seismograph Network miscellaneous stations, Seattle, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('II', 'IRIS/IDA Global Seismograph Network, Seattle and San Diego, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IIM', 'Instituto de Ingenier UNAM, Mexico City, Mexico');
INSERT INTO stations_stationnetwork (code, name) VALUES ('INDR', 'Inst. Nacional de Recursos Hidraulicos, Santo Domingo, Dominican Rep.');
INSERT INTO stations_stationnetwork (code, name) VALUES ('INEL', 'Idaho Nat. Engineering and Environmental Lab., Idaho Falls, Idaho, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('INET', 'Instituto Nicaragde Estudios Territoriales, Managua, Nicaragua');
INSERT INTO stations_stationnetwork (code, name) VALUES ('INMG', 'Instituto de Meteorologia, Lisbon, Portugal');
INSERT INTO stations_stationnetwork (code, name) VALUES ('INPP', 'Ignalina Nuclear Power Plant, Ignalina, Lithuania');
INSERT INTO stations_stationnetwork (code, name) VALUES ('INTV', 'INTEVEP, Caracas, Venezuela');
INSERT INTO stations_stationnetwork (code, name) VALUES ('INY', 'Cornell University, Ithaca, New York, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IPEC', 'tav fyziky ZemMasaryk University, Brno, Czech Republic');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IRSA', 'Institutul Roman de Seismologie Aplicata, Bucharest, Romania');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ISK', 'Kandilli Observatory and Earthquake Research Inst., Istanbul, Turkey');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IST', 'Istanbul Technical University, Maslak, Istanbul, Turkey');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ISTP', 'Instituto Superior Tecnico, Lisbon, Portugal');
INSERT INTO stations_stationnetwork (code, name) VALUES ('IU', 'IRIS/USGS Global Seismograph Network, Seattle and Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('JCK', 'Geologisches Landesamt Nordrhein-Westfalen, Krefeld, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('JEN', 'Inst. fwissenschaften, Friedrich-Schiller-Univ., Jena, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('JHI', 'Regional Research Laboratory, Jorhat, India');
INSERT INTO stations_stationnetwork (code, name) VALUES ('JMA', 'Japan Meteorological Agency, Tokyo, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('JSN', 'Jamaica Seismograph Network, Univ. of the West Indies, Mona, Jamaica');
INSERT INTO stations_stationnetwork (code, name) VALUES ('JSO', 'Jordan Seismological Observatory, Amman');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KAZK', 'Seismological Institute, Kazakhstan Academy of Sciences, Almaty');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KBC', 'Institut de Recherches Gogiques et Minis, Ekona, Cameroon');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KGS', 'Kansas Geological Survey, University of Kansas, Lawrence, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KISR', 'Kuwait Institute for Scientific Research, Safat, Kuwait');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KLM', 'Malaysian Meteorological Service, Petaling Jaya, Selangor, Malaysia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KORS', 'GSRAS, Kola Regional Seismological Center, Apatity, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KOWA', 'Ecole Nationale d''Ingeurs, Drtement de Gogie, Bamako, Mali');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KRSC', 'GSRAS, Kamchatka Regional Seismological Center, Petropavlovsk, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KRW', 'Geophysikalisches Institut, Karlsruhe, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KRYM', 'Crimean Geophysical Institute, Ukraine Academy of Science, Ukraine');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KUK', 'Ghana Geological Survey Department, Accra, Ghana');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KYRG', 'Institute of Seismology, Kyrgyzstan Academy of Sciences, Bishkek');
INSERT INTO stations_stationnetwork (code, name) VALUES ('KYT', 'Faculty of Science, Kyoto University, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LASA', 'Large Aperture Seismic Array, Billings, Montana, USA (closed)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LBTB', 'Geological Survey of Botswana, Lobatse, Botswana');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LDG', 'CEA Lab. de Dction et de Ghysique, Bruys-le-Chl, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LDN', 'University of Western Ontario, London, Ontario, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LDSN', 'Libyan Center for Remote Sensing and Space Science, Tripoli, Libya');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LEI', 'Institut fphysik und Geologie, UniversitLeipzig, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LGS', 'Lithuanian Geological Survey, Vilnius, Lithuania');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LIC', 'Station Ghysique de Lamto, N''Douci, Cote d''Ivoire');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LIM', 'Instituto Geofco del Perma, Peru');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LJC', 'Inst. of Geop. and Planet. Phys., UC San Diego, La Jolla, Calif, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LJU', 'ARSO, Urad za seizmologijo, Ljubljana, Slovenia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LLI', 'Istituto Internazionale di Vulcanologia--CNR, Catania, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LMM', 'Servico Meteorologico de Mobique, Maputo, Mozambique (closed)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LOA', 'Los Alamos Scientific Laboratories, Los Alamos, New Mexico, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LPA', 'Observatorio Astronomico, Universidad Nacional de La Plata, Argentina');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LPZ', 'Observatorio San Calixto, La Paz, Bolivia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LRSM', 'Long Range Seismic Monitoring Network, Garland, Texas, USA (closed)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LSZ', 'Geological Survey Department, Lusaka, Zambia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LUB', 'Texas Tech University, Lubbock, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LVM', 'Lawrence Livermore National Laboratory, Livermore, California, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LVV', 'Carpathian Seismo. Dept., Ukraine Academy of Science, Lviv, Ukraine');
INSERT INTO stations_stationnetwork (code, name) VALUES ('LWI', 'Departement de Ghysique, Lwiro, Democratic Republic of the Congo');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MBO', 'Institut de Recherche pour le Developpement, M''Bour, Senegal');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MDD', 'Instituto Geogrco y Catastral, Madrid, Spain');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MEL', 'Seismology Research Centre, Melbourne, Australia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MERI', 'Maharashtra Engineering Research Institute, Nashik, Maharashtra, India');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MES', 'Istituto Geofisico e Geodetico, Messina, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MEX', 'RESMAC, IIMAS-UNAM, Mexico City, Mexico (now part of UNM network)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MN', 'Mediterranean Very Broadband Seismograph Network (MedNet), Rome, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MNLO', 'USGS National Center for Earthquake Research, Menlo Park, Calif, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MNM', 'University of Minnesota, Minneapolis, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MOLD', 'Institute of Geophysics and Geology, Chisinau, Moldova');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MRB', 'Institut Cartogrc de Catalunya (ICC), Barcelona, Spain');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MSCO', 'Mesa State College, Grand Junction, Colorado, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MSKU', 'Universites Sciences et Techniques de Masuku, Franceville, Gabon');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MSO', 'University of Montana, Missoula, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MTAT', 'Mineral Research and Exploration Institute (MTA), Ankara, Turkey');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MUI', 'Geophysics Department, Ferdowsi University, Mashhad, Iran');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MVOV', 'Montserrat Volcano Observatory, Mango Hill, Montserrat');
INSERT INTO stations_stationnetwork (code, name) VALUES ('MX', 'Red Sismola Nacional de Mco (MNSN) BB stations, Mexico City');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NAI', 'Geology Department, University of Nairobi, Nairobi, Kenya');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NAO', 'NTNF/NORSAR, Kjeller, Norway');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NARS', 'NARS network, University of Utrecht, The Netherlands');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NASC', 'National Antarctic Scientific Center of Ukraine, Kiev, Ukraine');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NAT', 'Departamento de Fca Tea e Experimental, UFRN, Natal, Brazil');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NDI', 'India Meteorological Department, New Delhi, India');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NED', 'Delaware Geological Survey, Newark, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NEIC', 'USGS Nat. Earthquake Information Center, Golden, USA (and predecessors)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NERS', 'GSRAS, Northeastern Regional Seismological Center, Magadan, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NGY', 'RCSVDM, Graduate School of Environmental Studies, Nagoya Univ., Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NIC', 'Geological Survey Department, Nicosia, Cyprus');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NIED', 'Nat. Res. Inst. for Earth Sci. and Disaster Prevention, Tsukuba, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NIPR', 'National Institute of Polar Research, Tokyo, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NNC', 'Nat. Nuclear Center, Inst. of Geophysical Research, Almaty, Kazakhstan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NOU', 'Institut de Recherche pour le Developpement, Noumea, New Caledonia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NSAU', 'National Space Agency of Ukraine, Kiev, Ukraine');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NSSC', 'National Syrian Seismological Center, Damascus, Syria');
INSERT INTO stations_stationnetwork (code, name) VALUES ('NSSP', 'National Survey of Seismic Protection, Yerevan, Armenia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OBM', 'Mongolian Academy of Sciences, Ulaanbaatar, Mongolia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OBN', 'GSRAS, Russian National Seismological Center, Obninsk, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OGSO', 'OhioSeis Network, Ohio Geological Survey, Columbus, Ohio, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OMAN', 'Department of Earth Sciences, Sultan Qaboos University, Al-Khod, Oman');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OMPT', 'Observatoire Midi-Pyres, Toulouse, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OTT', 'Geological Survey of Canada, Ottawa, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OTTR', 'Geological Survey of Canada Regional Stations, Ottawa, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('OVO', 'Osservatorio Vesuviano, Naples, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PAL', 'Lamont-Doherty Earth Observatory, Palisades, New York, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PAR', 'Institut de Physique du Globe, Univ. P et M Curie, Paris, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PAS', 'USGS/CalTech, California Institute of Technology, Pasadena, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PDA', 'Instituto de Meteorologia, Obs. Afonso Chaves, Ponta Delgada, Azores');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PDG', 'Seizmoloski zavod Crne Gore, Podgorica, Montenegro, Serbia & Montenegro');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PEPP', 'Princeton Earth Physics Project, Princeton, New Jersey, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PINS', 'Pakistan Inst. of Nuclear Science and Technology, Rawalpindi, Pakistan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PIVS', 'Philippine Inst. of Volcanology & Seismology, Quezon City, Philippines');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PLV', 'Inst. of Geophysics, Vietnamese Acad. of Science and Technology, Hanoi');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PMG', 'Geological Survey, Port Moresby, Papua New Guinea');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PMR', 'NOAA, West Coast and Alaska Tsunami Warning Center, Palmer, Alaska, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PNNL', 'Pacific Northwest National Laboratory, Richland, Washington, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('POLR', 'POLARIS Project, Ottawa, Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PPT', 'Laboratoire de Ghysique, Papeete, French Polynesia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PRE', 'Council for Geoscience, Pretoria, South Africa');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PRT', 'Osservatorio San Domenico, Prato, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PS', 'Ocean Hemisphere Project (formerly POSEIDON), Tokyo, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PSNT', 'Public Seismic Network - PSN (homepage: www.seismicnet.com)');
INSERT INTO stations_stationnetwork (code, name) VALUES ('PTN', 'State University of New York, Potsdam, New York, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('QCP', 'Manila Observatory, Ateneo de Manila University, Manila, Philippines');
INSERT INTO stations_stationnetwork (code, name) VALUES ('QDM', 'Queensland Department of Mines, Brisbane, Australia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('QMB', 'University of Leeds, Yorkshire, England, UK');
INSERT INTO stations_stationnetwork (code, name) VALUES ('QUE', 'Pakistan Meteorological Department, Quetta, Pakistan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('QUI', 'Escuela Politica Nacional, Quito, Ecuador');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RAB', 'Geological Survey, Vulcanological Observatory, Rabaul, Papua New Guinea');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RDJ', 'Observatorio Nacional, Rio de Janeiro, Brazil');
INSERT INTO stations_stationnetwork (code, name) VALUES ('REN', 'University of Nevada, Reno, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('REX', 'Brigham Young University - Idaho, Rexburg, Idaho, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('REY', 'Vetofa lands, Reykjav Iceland');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RIPT', 'Research Inst. of Pulse Technique, Ministry for Atomic Energy, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RLP', 'Landeserdbebendienst Rheinland-Pfalz, Mainz, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RMOD', 'Russian Ministry of Defense, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ROM', 'Istituto Nazionale di Geofisica e Vulcanologia, Rome, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RS', 'Regional Seismic Test Network (RSTN), Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RSNC', 'Red Sica Nacional de Colombia, INGEOMINAS, BogotColombia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RSPR', 'Red Sica de Puerto Rico, Universidad de Puerto Rico, Mayag');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RUVS', 'Rede Universitaria de Vigilancia Sismovulcanica, SMiguel, Azores');
INSERT INTO stations_stationnetwork (code, name) VALUES ('RYD', 'King Saud University, Riyadh, Saudi Arabia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SAKL', 'Sakhalin Complex Research Institute, Novoalexandrovsk -- now SKHL net');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SAND', 'Sandia Laboratories, Albuquerque, New Mexico, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SAPN', 'Emergency Management Office, Saipan, Northern Mariana Islands');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SBS', 'Institut National de la Morologie, Tunis, Tunisia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SCP', 'Pennsylvania State University, State College, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SDD', 'Universidad Auta de Santo Domingo, Dominican Republic');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SEA', 'Geophysics Program, University of Washington, Seattle, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SEO', 'Korean Meteorological Agency, Seoul, South Korea');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SFS', 'Real Instituto y Observatorio de la Armada, San Fernando, Spain');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SHV', 'Inst. of Seismology and Volcanology, Kyushu Univ., Shimabara, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SJA', 'Instituto Nacional de Prevenciica, San Juan, Argentina');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SKHL', 'GSRAS, Sakhalin Regional Seismological Ctr., Yuzhno-Sakhalinsk, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SKO', 'Seismological Observatory, Skopje University, Macedonia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SLC', 'University of Utah, Salt Lake City, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SLCI', 'University of Utah Research Institute, Salt Lake City, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SLCY', 'University of Utah Yellowstone network, Salt Lake City, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SLM', 'St. Louis University, St. Louis, Missouri, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SNET', 'Servicio Nacional de Estudios Territoriales, San Salvador, El Salvador');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SNM', 'New Mexico Institute of Mining and Technology, Socorro, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SNSN', 'Saudi NSN, King Abdulaziz City for Sci. and Tech., Riyadh, Saudi Arabia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SOF', 'Section of Seismology, Bulgarian Academy of Sciences, Sofia, Bulgaria');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SORS', 'Republic Hydrometeorological Institute, Banja Luka, Bosnia-Herzegovina');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SPGM', 'Service de Physique du Globe, Rabat Agdal, Morocco');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SR', 'Seismic Research Observatory Network (SRO), Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SRPD', 'Savannah River Laboratory, Aiken, South Carolina, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SSNC', 'Centro Nacional de Investigaciones Sismolas, Santiago de Cuba, Cuba');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SSO', 'Osservatorio Geofisico Sperimentale, Macerata, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('STR', 'ole et Observatoire des Sciences de la Terre, Strasbourg, France');
INSERT INTO stations_stationnetwork (code, name) VALUES ('STU', 'Institut fphysik der UniversitStuttgart, Stuttgart, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SVA', 'Department of Mineral Resources, Suva, Fiji');
INSERT INTO stations_stationnetwork (code, name) VALUES ('SXNET', 'Ssiches Landesamt felt und Geologie, Dresden, Germany');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TAJK', 'Tajikistan Academy of Sciences, Dushanbe, Tajikistan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TAN', 'Institut et Observatoire Ghysique d''Antananarivo, Madagascar');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TAP', 'Central Weather Bureau, Taipei, Taiwan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TATO', 'Institute of Earth Sciences, Academia Sinica, Taipei, Taiwan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TAU', 'University of Tasmania, Hobart, Australia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TBU', 'Environmental Physics Institute, Tibet University, Lhasa, Tibet, China');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TEH', 'Institute of Geophysics, University of Tehran, Tehran, Iran');
INSERT INTO stations_stationnetwork (code, name) VALUES ('THE', 'Geophysical Laboratory, University of Thessaloniki, Greece');
INSERT INTO stations_stationnetwork (code, name) VALUES ('THR', 'Intl. Inst. of Earthquake Engineering and Seismology, Tehran, Iran');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TIF', 'Inst. of Geophysics, Academy of Sciences of Georgia, Tbilisi, Georgia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TIR', 'Seismological Center, Academy of Sciences of Albania, Tirana, Albania');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TOH', 'AOB, Graduate School of Science, Tohoku University, Sendai, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TRI', 'Ist. Nazle. di Oceanografia e di Geofisica Sperimentale, Trieste, Italy');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TRKM', 'Institute of Seismology, Turkmenistan Academy of Science, Ashgabat');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TRN', 'University of the West Indies, St. Augustine, Trinidad');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TS', 'TERRAscope Network, Pasadena, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TUL', 'Oklahoma Geological Survey, Leonard, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TVA', 'Tennessee Valley Authority, Knoxville, Tennessee, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TW', 'Broadband Array in Taiwan for Seismology (BATS), Taipei, Taiwan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('TZN', 'University of Dar es Salaam, Tanzania');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UAV', 'Laboratorio de Geofca, Universidad de los Andes, Mda, Venezuela');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UBC', 'University of British Columbia, Vancouver, B.C., Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UBIC', 'Univ. de Barcelona i Institut d''Estudis Catalans, Barcelona, Spain');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UCC', 'Observatoire Royal de Belgique, Uccle, Brussels, Belgium');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UCR', 'Seccion de Sismolog Univ. de Costa Rica, San JosCosta Rica');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UDEC', 'Universidad de ConcepciConcepciChile');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UDO', 'Centro de Sismolog Universidad de Oriente, CumanVenezuela');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UNAH', 'Universidad Nacional Auta de Honduras, Tegucigalpa, Honduras');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UNM', 'Instituto de Geofca, UNAM, Mexico City, DF, Mexico');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UPA', 'Instituto de Geociencias, Universidad de PanamPanama');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UPP', 'Seismological Institute, Uppsala, Sweden');
INSERT INTO stations_stationnetwork (code, name) VALUES ('URS', 'Kochi University, Kochi, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('US', 'United States National Seismic Network (USNSN), Golden USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('USAF', 'US Air Force Technical Applications Center, Melbourne, Florida, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('USAV', 'USGS Alaska Volcano Observatory, Anchorage, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('USBR', 'US Bureau of Reclamation, Denver, Colorado, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('USC', 'University of Southern California, Los Angeles, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('USGS', 'US Geological Survey--other than ABQ, AGS, MNLO, NEIC, HVO and USAVO');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UTSU', 'Utsunomiya University, Japan');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UVC', 'Universidad del Valle, Cali, Colombia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('UZBK', 'Institute of Seismology, Uzbekistan Academy of Sciences, Tashkent');
INSERT INTO stations_stationnetwork (code, name) VALUES ('VAO', 'Inst. de Astron., Geof. e Ciias Atmos., Univ. de SPaulo, Brazil');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WAR', 'Instytutu Geofizyki, Polskeij Akademii Nauk, Warsaw, Poland');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WCTN', 'GSC Western Canada Telemetered Network, Sidney, B.C., Canada');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WEL', 'Institute of Geological and Nuclear Sciences, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELA', 'IGNS Auckland network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELC', 'IGNS Clyde network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELE', 'IGNS Taranaki network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELH', 'IGNS Hawkes Bay network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELO', 'IGNS Tongariro Volcanic network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELP', 'IGNS Pukaki network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELR', 'IGNS Rotorua network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELT', 'IGNS Taupo network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WELW', 'IGNS Wellington network, Lower Hutt, New Zealand');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WES', 'Weston Observatory, Boston College, Weston, Massachusetts, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WIEN', 'Institut feorologie und Geophysik, Univ. Wien, Vienna, Austria');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WIHG', 'Wadia Institute of Himalayan Geology, Dehra Dun, India');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WWC', 'Woodward-Clyde Consultants, California, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('WWSS', 'Worldwide Standard Seismograph Network (WWSSN), Albuquerque, USA');
INSERT INTO stations_stationnetwork (code, name) VALUES ('YARS', 'GSRAS Siberian Branch, Yakutiya Regional Seis. Center, Yakutsk, Russia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ZAG', 'Geophysical Institute, University of Zagreb, Croatia');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ZAMG', 'ZentralAnstalt feorologie und Geodynamik, Vienna, Austria');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ZON', 'Universidad Nacional de San Juan, San Juan, Argentina');
INSERT INTO stations_stationnetwork (code, name) VALUES ('ZUR', 'Schweizerischer Erdbebendienst, Z Switzerland');
